### ISSUE TITLE
Stopped working since transition to x.com?

### ISSUE THREAD

**Issue by JulienMaille** [ZakariaMQ/twitter-account-unlocker#1]
I may be wrong but I gave this unlocker a try and the result I get from all posts all contain
`Due to a technical issue, we couldn't complete this request. Please try again.`

**Comment by ZakariaMQ** [comment]
it may be the captcha token isn't correct
I will try it and let you know

**Comment by JulienMaille** [comment]
Do you mean the sitekey? I believe it is still `0152B4EB-D2DC-460A-89A1-629838B529C9`

**Comment by ZakariaMQ** [comment]
no, I mean the token gets returned by Capsolver

**Comment by JulienMaille** [comment]
May I ask why you have the captcha solved and posted twice in a row?
https://github.com/ZakariaMQ/twitter-account-unlocker/blob/aa33de22647e2def12df3bf2c405b3d0d21c9fd1/main.py#L112-L123

**Comment by ZakariaMQ** [comment]
cause twitter require to be solved twice
